tupas_registration.settings:
  type: config_object
  label: 'Tupas registration'
  mapping:
    use_tupas_name:
      type: integer
      label: 'Always attempt to use username provided by TUPAS service'
    disable_form:
      type: integer
      label: 'Disable registration form and generate accounts automatically'
