tupas_registration.settings:
  type: config_object
  label: 'Tupas registration'
  mapping:
    generate_random_username:
      type: integer
      label: 'Always generate a random username for the user'
    disable_form:
      type: integer
      label: 'Disable registration form and generate accounts automatically'
